.nh
.TH Nginx 1.16 server and a reverse proxy server container image
.PP
This container image includes Nginx 1.16 server and a reverse server for OpenShift and general usage.
Users can choose between RHEL, CentOS and Fedora based images.
The RHEL images are available in the Red Hat Container Catalog
\[la]https://access.redhat.com/containers/\[ra],
the CentOS images are available on Docker Hub
\[la]https://hub.docker.com/r/centos/\[ra],
and the Fedora images are available in Fedora Registry
\[la]https://registry.fedoraproject.org/\[ra]\&.
The resulting image can be run using podman
\[la]https://github.com/containers/libpod\[ra]\&.

.PP
Note: while the examples in this README are calling \fB\fCpodman\fR, you can replace any such calls by \fB\fCdocker\fR with the same arguments.

.SH Description
.PP
Nginx is a web server and a reverse proxy server for HTTP, SMTP, POP3 and IMAP
protocols, with a strong focus on high concurrency, performance and low memory usage. The container
image provides a containerized packaging of the nginx 1.16 daemon. The image can be used
as a base image for other applications based on nginx 1.16 web server.
Nginx server image can be extended using Openshift's \fB\fCSource\fR build feature.

.SH Usage
.PP
For this, we will assume that you are using the \fB\fCrhel8/nginx\-116\fR image, available via \fB\fCnginx:1.16\fR imagestream tag in Openshift.
Building a simple sample\-app
\[la]https://github.com/sclorg/nginx-container/tree/master/1.16/test/test-app\[ra] application
in Openshift can be achieved with the following step:

.PP
.RS

.nf
```
oc new\-app nginx:1.16\~https://github.com/sclorg/nginx\-container.git \-\-context\-dir=1.16/test/test\-app/
```

.fi
.RE

.PP
The same application can also be built using the standalone S2I
\[la]https://github.com/openshift/source-to-image\[ra] application on systems that have it available:

.PP
.RS

.nf
```
$ s2i build https://github.com/sclorg/nginx\-container.git \-\-context\-dir=1.16/test/test\-app/ rhel8/nginx\-116 nginx\-sample\-app
```

.fi
.RE

.PP
\fBAccessing the application:\fP

.PP
.RS

.nf
$ curl 127.0.0.1:8080

.fi
.RE

.SH S2I build support
.PP
This image can be extended in Openshift using the \fB\fCSource\fR build strategy or via the standalone
source\-to\-image
\[la]https://github.com/openshift/source-to-image\[ra] application (where available).
S2I build folder structure:

.PP
\fB\fB\fC\&./nginx.conf\fR\fP\-\-
       The main nginx configuration file

.PP
\fB\fB\fC\&./nginx\-\&cfg/*.conf\fR\fP
       Should contain all nginx configuration we want to include into image

.PP
\fB\fB\fC\&./nginx\-\&default\-\&cfg/*.conf\fR\fP
       Contains any nginx config snippets to include in the default server block

.PP
\fB\fB\fC\&./nginx\-\&start/*.sh\fR\fP
       Contains shell scripts that are sourced right before nginx is launched

.PP
\fB\fB\fC\&./nginx\-\&perl/*.pm\fR\fP
       Contains perl modules to be use by \fB\fCperl\_modules\fR and \fB\fCperl\_require\fR directives

.PP
\fB\fB\fC\&./\fR\fP
       Should contain nginx application source code

.SH Environment variables and volumes
.PP
The nginx container image supports the following configuration variable, which can be set by using the \fB\fC\-e\fR option with the podman run command:

.PP
\fB\fB\fCNGINX\_LOG\_TO\_VOLUME\fR\fP
       When \fB\fCNGINX\_LOG\_TO\_VOLUME\fR is set, nginx logs into \fB\fC/var/log/nginx/\fR\&. In case of RHEL\-\&7 and CentOS\-\&7 images, this is a symlink to \fB\fC/var/opt/rh/rh\-nginx116/log/nginx/\fR\&.

.PP
You can mount your own web root like this:

.PP
.RS

.nf
$ podman run \-v <DIR>:/var/www/html/ <container>

.fi
.RE

.PP
You can replace <DIR> with location of your web root. Please note that this has to be an \fBabsolute\fP path, due to podman requirements.

.SH Troubleshooting
.PP
By default, nginx access logs are written to standard output and error logs are written to standard error, so both are available in the container log. The log can be examined by running:

.PP
.RS

.nf
podman logs <container>

.fi
.RE

.PP
\fBIf \fB\fCNGINX\_LOG\_TO\_VOLUME\fR variable is set, nginx logs into \fB\fC/var/log/nginx/\fR\&. In case of RHEL\-\&7 and CentOS\-\&7 images, this is a symlink to \fB\fC/var/opt/rh/rh\-nginx116/log/nginx/\fR, which can be mounted to host system using the container volumes.\fP

.SH See also
.PP
Dockerfile and other sources for this container image are available on
https://github.com/sclorg/nginx\-container.
In that repository you also can find another versions of Python environment Dockerfiles.
Dockerfile for CentOS is called \fB\fCDockerfile\fR, Dockerfile for RHEL7 is called \fB\fCDockerfile.rhel7\fR,
for RHEL8 it's \fB\fCDockerfile.rhel8\fR and the Fedora Dockerfile is called Dockerfile.fedora.
